# Generated by Django 2.1.4 on 2019-01-03 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Position', to_field='name'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
