# Generated by Django 2.1.4 on 2019-01-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_position_vocation_on_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='vocation_on_position',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
