# Generated by Django 2.1.4 on 2019-01-03 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20190103_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hired',
            field=models.DateField(default=datetime.date(2019, 1, 3)),
        ),
    ]
