# Generated by Django 2.1.4 on 2019-01-03 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_hired'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary+', to='account.Position'),
        ),
    ]
