# Generated by Django 2.1.4 on 2019-01-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_user_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='salary',
        ),
    ]
