# Generated by Django 2.1.4 on 2019-01-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20190104_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='salary',
            field=models.CharField(default=3200, max_length=10),
        ),
    ]
