# Generated by Django 2.1.4 on 2019-01-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20190104_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
