# Generated by Django 2.1.4 on 2019-01-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20190104_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='salary',
            field=models.CharField(blank=True, default=3200, max_length=10, null=True),
        ),
    ]
