# Generated by Django 2.1.4 on 2019-01-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20190106_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Cities'},
        ),
    ]
