# Generated by Django 2.1.4 on 2019-01-13 13:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDayOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_from', models.DateTimeField()),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'sickness'), (2, 'vacation'), (3, 'day off')], default=0)),
                ('reason', models.CharField(max_length=256)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Done'), (1, 'Confirmed'), (2, 'Rejected')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='sickness_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='vacations_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='hired',
            field=models.DateField(default=datetime.date(2019, 1, 13)),
        ),
        migrations.AddField(
            model_name='requestdayoff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayoffs', to=settings.AUTH_USER_MODEL),
        ),
    ]
