# Generated by Django 2.1.4 on 2019-01-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20190110_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdayoff',
            name='name',
            field=models.CharField(default='Request day application from <django.db.models.fields.related.ForeignKey>', max_length=100),
        ),
    ]
