# Generated by Django 2.1.4 on 2019-01-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_requestdayoff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdayoff',
            name='hr_commentary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
