# Generated by Django 2.1.4 on 2019-01-19 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20190116_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdayoff',
            name='date_to',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestdayoff',
            name='reason',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='requestdayoff',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'sickness'), (2, 'vacation'), (3, 'day off')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='hired',
            field=models.DateField(default=datetime.date(2019, 1, 19)),
        ),
    ]
